version: '3'
services:
  healthcheck:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_DESTINATION_CHAT_ID=${TELEGRAM_DESTINATION_CHAT_ID}
      - URL_TO_CHECK=${URL_TO_CHECK}